version: "3.7"

services:
  app:
    container_name: react-web
    build: .
    volumes:
      - .:/app
    ports:
      - 80:80
  mongos:
    container_name: mongos
    hostname: mongos
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: mydatabase

    ports:
      - 27017:27017
    volumes:
      - ./mongoDB/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  api:
    container_name: api
    hostname: api
    build: ./api
    restart: always
    ports:
      - 3000:3000
    links:
      - mongos
    depends_on:
      - mongos
    environment:
      WAIT_HOSTS: mongos:27017
