version: "3.7"

services:
  app:
    container_name: react-web
    build: .
    ports:
      - 80:80
  mongos:
    container_name: mongos
    build: ./mongoDB
    ports:
      - 27017:27017

  api:
    container_name: api
    build: ./api
    restart: always
    ports:
      - 3000:3000
    links:
      - mongos
    depends_on:
      - mongos
    environment:
      WAIT_HOSTS: mongos:27017
      MONGOHOST: mongos
